### PR TITLE
fix: types file path

### PR DESCRIPTION
**Pull request by mesqueeb**

### CODE REVIEW

**Comment by mesqueeb** [comment]
@Rabbitzzc is it possible to merge and release this on npm? because currently there is no TS compatibility until this is fixed.

**Comment by mesqueeb** [comment]
@Rabbitzzc thanks! Now just pending the NPM release:
https://www.npmjs.com/package/tiny-replace-files

**Comment by Rabbitzzc** [comment]
Sorry. But there seems to be something wrong with my npm account. I'm trying to log in

**Comment by mesqueeb** [comment]
😱

**Pull request merged**
